### PR TITLE
chore(ip 2.0.1): ip version upgrade

### PR DESCRIPTION
**Pull request by rohittarpara**
#### Details

ip version upgrade to 2.0.1 for Accessibility Insights for Action

##### Motivation

Upgrade the ip version to latest 2.0.1 in Accessibility Insights
for Action.

https://dev.azure.com/mseng/1ES/_componentGovernance/1010/alert/201464?typeId=286939
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #0000
- [X] Added relevant unit test for your changes. (`yarn test`)
- [X] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

**Comment by madalynrose** [comment]
@rohittarpara shouldn't this have a change in `package.json` as well?

**Comment by rohittarpara** [comment]
> @rohittarpara shouldn't this have a change in `package.json` as well?

@madalynrose No, because In the package.json file, i could not find the ip package.

**Comment by madalynrose** [comment]
@rohittarpara if that's the case, it's being managed by a different package and this change will be overwritten by any `yarn install` calls. If we need a particular version for security, we should add a [yarn resolution](https://github.com/microsoft/accessibility-insights-action/blob/main/package.json#L74) for it.

**Comment by rohittarpara** [comment]
@madalynrose i have added " "ip@^2.0.0": "^2.0.1"" in package.json file, can you please verify.

**Review by madalynrose — APPROVED** [review]

**Pull request merged**
